spring:
  application:
    name: SzoftverfejlesztesMernokoknek

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./DB
    username: admin
    password: admin

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
#       ddl-auto: update


web:
  cors:
    allowedOrigins: "*"
    allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
    allowedHeaders: "Requestor-Type"
    exposedHeaders: "X-Get-Header"


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
      requestMatchers: "/api/auth/**"
